FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.cn,direct
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/api .
COPY .env .
COPY migrations ./migrations
COPY seeders ./seeders
EXPOSE 8000
CMD ["./api"]