apiVersion: v1
kind: ConfigMap
metadata:
  name: bankx-config
data:
  SERVER_PORT: "8000"
  LOG_LEVEL: "info"
  POSTGRES_HOST: "host.docker.internal"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "capstone"
  REDIS_ADDR: "host.docker.internal:6379"
  REDIS_DB: "0"
  KAFKA_BROKERS: "host.docker.internal:9092"
  KAFKA_TOPIC: "transactions"
  KAFKA_GROUP_ID: "worker-group"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"