apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankx-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankx-api
  template:
    metadata:
      labels:
        app: bankx-api
    spec:
      containers:
      - name: api
        image: capstone-project-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: bankx-config
        - secretRef:
            name: bankx-secret
        resources:
          requests:
            cpu: "200m"
            memory: "150Mi"
          limits:
            cpu: "700m"
            memory: "300Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3