apiVersion: v1
kind: Secret
metadata:
  name: bankx-secret
type: Opaque
stringData:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  MONGO_URI: "mongodb://mongo:capstone123@host.docker.internal:27017/capstone?authSource=admin"
  REDIS_PASSWORD: ""